name: Triggers
run-name: ¡Estoy aprendiendo a usar diferentes Triggers!
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, symchronize, reopened]
    paths:
      - '**.py'
  issues:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje favorito'
        default: Python
        required: true
        type: choice
        options:
          - Python
          - JavaScript
          - Go
      nombre:
        descripcion: 'Tu nombre'
        required: true
        default: Jhonatan
        type: string
  schedule:
    - cron: '15 22 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      - name: script-runing
        run: python hello_world.py 
  hola-mundo:
    if: ${{ githun.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: definir variable
        run: echo "USERNAME=${{ inputs.actor }}" >> $GITHUB_ENV
      - name: script-runing
        run: python hello_world.py 
